typography_spectrum: 0.95734
color:
  brandColors:
    - '#101010'
    - '#303030'
    - '#d9d9d9'
    - '#a4a4a4'
    - '#797979'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.89743
analytics:
  google: null
  facebook: null
  twitter: null
name: chris.lemmon.com
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
